name: impfi
version: 0.0.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
description: Package description here.
requirements:
- python ^3.5
- sqlalchemy
- python-telegram-bot
- requests
- bs4 ^0.0.1
- databind.core ^0.11.0
- databind.yaml ^0.1.3
entrypoints:
  impfi.api.IPlugin:
  - dachau = impfi.contrib.de.bavaria.dachau:DachauMedPlugin
